version: "3"

networks:
  database:
  server:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - server
    links:
      - php
      - composer

  php:
    build:
      context: ./
      dockerfile: ./php.dockerfile
    volumes:
      - ./app:/var/www/app
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - database
      - server
    env_file: variables.env
    links:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/runtime/mysql:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    networks:
      - database
    env_file: variables.env

  composer:
    image: composer
    command: install
    volumes:
      - ./app:/app
